#!/usr/bin/env python3
import sys, os, boto3
import transform as tr
import logging
from botocore.exceptions import ClientError
from pathlib import Path
from datetime import datetime

def runPatronFineTransform():
    path="/data/sierra"
    filename="{0}/innopac.charge"
    path = Path(filename)
    if path.is_file():
        now = datetime.now()
        new_filename="{0}.{1}".format(filename,now.strftime("%Y-%m-%d"))
        path.rename(new_filename)
        df=tr.transform(new_filename)
        pfile_name="processed-{0}.csv".format(new_filename)
        df.to_csv(pfile_name, sep='|', index=False)
        s3_client = boto3.client('s3')
        try:
            response = s3_client.upload_file(pfile_name, "cubl-patron-fines", object_name)
        except ClientError as e:
            logging.error(e)

if __name__ == "__main__":
    runPatronFineTransform()